apiVersion: v1
kind: Service
metadata:
  name: {{ include "discovery_redis.fullname" . | replace "_" "-" }}
spec:
  type: {{ .Values.service.type }}
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
    - port: {{ .Values.service.port}}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "discovery_redis.selectorLabels" . | nindent 4 }}
