apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.route.name }}
spec:
  host: {{ .Values.route.path }}
  port:
    targetPort: {{ .Values.service.port }}
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
  to:
    kind: Service
    name: {{ .Values.service.name }}
    weight: 100
  wildcardPolicy: None
  status:
    ingress:
    - conditions:
      host: {{ .Values.route.path }}
      wildcardPolicy: None

