apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "celery_worker.fullname" . | replace "_" "-" }}
  labels:
    {{- include "celery_worker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.autoscaling.minReplicas }}
  selector:
    matchLabels:
      {{- include "celery_worker.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "celery_worker.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccount: {{ include "discovery.globalServiceAccountName" . }}
      serviceAccountName: {{ include "discovery.globalServiceAccountName" . }}
      restartPolicy: Always
      volumes:
      - name: {{ .Release.Name }}-data-volume-claim
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-data-volume-claim
      - name: {{ .Release.Name }}-log-volume-claim
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-log-volume-claim
      containers:
        - name: {{ .Chart.Name | replace "_" "-" }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/sh", "-c", "/deploy/entrypoint_celery_worker.sh" ]
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          volumeMounts:
          - mountPath: /var/data
            name: {{ .Release.Name }}-data-volume-claim
          - mountPath: /var/log
            name: {{ .Release.Name }}-log-volume-claim
          env:
            - name: ANSIBLE_REMOTE_TMP
              value: {{ .Values.ansible.remoteTmp }}
            - name: ANSIBLE_LOCAL_TEMP
              value: {{ .Values.ansible.localTemp }}
            - name: DJANGO_SECRET_PATH
              value: {{ .Values.global.djangoSecretPath }}
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: django-secret-key
                  name: discovery-secrets
            - name: REDIS_HOST
              value: {{ include "discovery.redis-host" . }}
            - name: REDIS_PASSWORD
              value: {{  .Values.global.redisPassword }}
