apiVersion: v1
kind: Service
metadata:
  name: {{ include "discovery-redis.fullname" . }}
spec:
  type: ClusterIP
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
    - port: {{ .Values.service.port}}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "discovery-redis.selectorLabels" . | nindent 4 }}
